services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8080:80"
    depends_on:
      - app
    container_name: laravel-blog_nginx

  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www
    container_name: laravel-blog_app
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
        MYSQL_DATABASE: laravel-blog
        MYSQL_ROOT_PASSWORD: root
    ports:
      - "8101:3306"
    container_name: laravel-blog_db

volumes:
  db-data:
    driver: local
